import express from 'express'; import bcrypt from 'bcrypt'; import jwt from 'jsonwebtoken'; import {z} from 'zod'; import {User,Customer,Event,Service,Deliverable,Payment,Expense,Workflow} from './models.js'; import {auth,validate} from './middleware.js';
const router=express.Router(), models={customers:Customer,events:Event,services:Service,deliverables:Deliverable,payments:Payment,expenses:Expense,workflow:Workflow};
const workflowSteps=['PixStudio Upload','Drive Upload','Reel Uploaded','Teaser Uploaded','Highlight Uploaded','Selection Completed','Downloaded for Design','Design Completed','Sent for Approval','Sent for Print','Ready to Deliver','Traditional Video Ready','Delivered'];
const sign=(user)=>jwt.sign({id:user._id,email:user.email},process.env.JWT_SECRET,{expiresIn:'7d'});
const cookie=(res,token)=>res.cookie('token',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.NODE_ENV==='production'?'none':'lax',maxAge:604800000});
router.post('/auth/login',validate(z.object({email:z.string().email(),password:z.string().min(1)})),async(req,res)=>{const u=await User.findOne({email:req.body.email});if(!u||!await bcrypt.compare(req.body.password,u.password))return res.status(401).json({message:'Invalid email or password'});cookie(res,sign(u));res.json({user:{email:u.email}})});
router.post('/auth/logout',(req,res)=>{res.clearCookie('token');res.status(204).end()}); router.get('/auth/me',auth,async(req,res)=>res.json({user:{email:req.user.email}}));
router.post('/finance/verify-pin',auth,validate(z.object({pin:z.string().regex(/^\d{6}$/)})),async(req,res)=>{const u=await User.findById(req.user.id);if(!await bcrypt.compare(req.body.pin,u.financePin))return res.status(401).json({message:'Incorrect PIN'});const token=jwt.sign({id:u._id,finance:true},process.env.JWT_SECRET,{expiresIn:'30m'});res.cookie('finance',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.NODE_ENV==='production'?'none':'lax',maxAge:1800000});res.json({ok:true})});
router.get('/dashboard',auth,async(req,res)=>{const now=new Date(), today=new Date(now.getFullYear(),now.getMonth(),now.getDate());const [totalCustomers,todayShoots,upcoming,pending,delivered,recentCustomers,recentDeliverables]=await Promise.all([Customer.countDocuments(),Event.countDocuments({date:{$gte:today,$lt:new Date(+today+86400000)}}),Event.find({date:{$gte:today}}).sort('date').limit(8).populate('customer','customerName'),Deliverable.countDocuments({status:{$ne:'Delivered'}}),Deliverable.countDocuments({status:'Delivered'}),Customer.find().sort('-createdAt').limit(5),Deliverable.find().sort('-updatedAt').limit(5).populate('customer','customerName')]);res.json({stats:{totalCustomers,todayShoots,upcomingEvents:upcoming.length,pendingDeliverables:pending,deliveredProjects:delivered},upcoming,recentCustomers,recentDeliverables})});
router.get('/customers/:id/overview',auth,async(req,res)=>{const id=req.params.id;const [customer,events,services,deliverables,payments,expenses,workflow]=await Promise.all([Customer.findById(id),Event.find({customer:id}).sort('date'),Service.find({customer:id}),Deliverable.find({customer:id}),Payment.find({customer:id}).sort('-date'),Expense.find({customer:id}).sort('-date'),Workflow.findOne({customer:id})]);if(!customer)return res.status(404).json({message:'Customer not found'});res.json({customer,events,services,deliverables,payments,expenses,workflow})});
for(const [path,Model] of Object.entries(models)){router.get('/'+path,auth,async(req,res)=>{const {page=1,limit=20,search,customer}=req.query;let q=customer?{customer}:{};if(search&&path==='customers')q={$or:['customerName','mobileNumber'].map(k=>({[k]:{$regex:search,$options:'i'}}))};const [data,total]=await Promise.all([Model.find(q).sort('-createdAt').skip((page-1)*limit).limit(+limit).populate('customer','customerName'),Model.countDocuments(q)]);res.json({data,total,page:+page,pages:Math.ceil(total/limit)})});router.post('/'+path,auth,async(req,res)=>{if(path==='workflow'&&!req.body.steps)req.body.steps=workflowSteps.map(name=>({name}));const doc=await Model.create(req.body);res.status(201).json(doc)});router.patch('/'+path+'/:id',auth,async(req,res)=>{const doc=await Model.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!doc)return res.status(404).json({message:'Not found'});res.json(doc)});router.delete('/'+path+'/:id',auth,async(req,res)=>{const doc=await Model.findByIdAndDelete(req.params.id);if(!doc)return res.status(404).json({message:'Not found'});res.status(204).end()})}
router.get('/finance/summary',auth,async(req,res)=>{try{jwt.verify(req.cookies.finance,process.env.JWT_SECRET);const [revenue,expenses,services,payments]=await Promise.all([Payment.aggregate([{$group:{_id:null,total:{$sum:'$amount'}}}]),Expense.aggregate([{$group:{_id:null,total:{$sum:'$amount'}}}]),Service.aggregate([{$group:{_id:null,total:{$sum:'$price'}}}]),Payment.find().populate('customer','customerName').sort('-date').limit(10)]);const paid=revenue[0]?.total||0,spent=expenses[0]?.total||0,total=services[0]?.total||0;res.json({revenue:paid,expenses:spent,profit:paid-spent,pending:Math.max(0,total-paid),recentPayments:payments})}catch{res.status(403).json({message:'Finance PIN verification required'})}});
export default router;
